### ISSUE TITLE
Fetch, Pull, and Push buttons are only active when master is selected 

### ISSUE THREAD

**Issue by thomasroefer** [brotherbard/gitx#56]
The Fetch, Pull, and Push buttons in the lower left corner are only active when the master is selected. Technically, fetch does not depend on the branch selected, and the other two buttons could work on other branches than "master" as well.

**Comment by brotherbard** [comment]
They are only active when the selected branch has been setup as a tracking branch for a remote branch. These buttons do the default action. This is because there can be multiple remotes and GitX can't know which one to fetch/pull/push from/to.

If you want to push a branch that is not tracking use the contextual menu and select a remote to push to.

**Comment by thomasroefer** [comment]
I see. This one is related to issue 54. If a local branch was created by "Create branch", it is a tracking branch, and the buttons work.
