### ISSUE TITLE
"Show history of file" broken

### ISSUE THREAD

**Issue by thirashima** [brotherbard/gitx#66]
In the last experimental build (Sep-20-2010.2), while browsing in tree mode, if you right-click on a file and select "Show history of file" from the context menu, GitX appears to take you to the last commit that affected that file, but it won't be in a chronological list of just the file's history, it will be in the repository's main commit history.

**Comment by brotherbard** [comment]
This is by design. There are arrow buttons next to the search field that will allow you to step through the commits that changed that file. The reason is so that you can see where the commits are in the project's history (what branch it's in for example).

There is also a feature in [laullon's](http://github.com/laullon/gitx) fork that I will be adding soon that has a more focused view of a file's history.
